name: DevSecOps CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # 3. Install dependencies
    - name: Install dependencies
      run: npm install

    # 4. Run tests
    - name: Run tests
      run: npm test

    # 5. SonarCloud Scan (SAST)
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=shindeabhi1
          -Dsonar.projectKey=shindeabhi1_node-devops
          -Dsonar.sources=.

    # 6. Build Docker image
    - name: Build Docker image
      run: docker build -t node-devops-app .

    # 7. Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
